name: CI/CD Fullstack Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./VTI_Galaxy_BE
          file: ./VTI_Galaxy_BE/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vti_backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./VTI_Galaxy_FE
          file: ./VTI_Galaxy_FE/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vti_frontend:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/VTI_Galaxy
            git pull origin main
            docker compose pull
            docker compose up -d --build
