version: "3.9"
services:
  db:
    image: postgres:15
    container_name: vti_galaxy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: VTI_Galaxy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      
      dockerfile: VTI_Galaxy_BE/Dockerfile
    container_name: vti_galaxy_backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/VTI_Galaxy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JACKSON_DATE_FORMAT=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      - SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS=false
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB
      - JWT_SECRET=QkRSRVZJRU5ORk9UQU5GRVhNUExFT05HRVZFTlRVUkVTSEFQSkZKQUxLR0RGR0hKTUtOWEFCasdasdasdasdasdasdasdasdasd
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=hoangleedz32@gmail.com
      - SPRING_MAIL_PASSWORD=onxx xyqx kzha qaqj
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=5000
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=5000
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=5000
      - SPRING_MAIL_PROTOCOL=smtp
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - VNP_PAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNP_RETURN_URL=http://localhost:8082/vnpay-payment/get
      - VNP_TMN_CODE=JNU30JRD
      - VNP_HASH_SECRET=R4W169703FEJMKKHK9SCB21WK7RI6BEE
      - VNP_API_URL=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_OPEN_IN_VIEW=false
    depends_on:
      - db

  frontend:
    build:
      context: ./VTI_Glaxy_FE
      dockerfile: Dockerfile
    container_name: vti_galaxy_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
