version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vti_galaxy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: VTI_Galaxy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./VTI_Galaxy_BE
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./VTI_Galaxy_BE/src/main/java/.env
    depends_on:
      - db
      

  frontend:
    build:
      context: ./VTI_Glaxy_FE
      dockerfile: Dockerfile
    ports:
      - "5173:80"

volumes:
  postgres_data:
