FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /app
COPY VTI_Galaxy_BE/pom.xml .
COPY VTI_Galaxy_BE/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
CMD ["java", "-jar", "app.jar", "--server.port=8082"]
