services:
  - type: web
    name: spring-boot-app
    runtime: docker
    rootDir: VTI_Galaxy_BE
    dockerfilePath: Dockerfile
    plan: starter
    region: oregon # hoặc chọn vùng khác như frankfurt
    dockerCommand: java -jar /app.jar # Giả định ứng dụng được đóng gói thành file JAR
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xms512m -Xmx1024m" # Cấu hình bộ nhớ cho JVM
      - key: SPRING_JACKSON_DATE_FORMAT
        value: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
      - key: SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: spring-boot-db
          property: connectionString
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: spring-boot-db
          property: connectionString

databases:
  - name: spring-boot-db
    databaseName: springboot
    user: springbootuser
    plan: starter
    region: oregon # Phải khớp với vùng của service
    ipAllowList: [] # Chặn tất cả kết nối bên ngoài, chỉ cho phép từ service