name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main   # hoặc nhánh bạn muốn deploy (vd: webapp)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: VTI_Glaxy_FE

      - name: Build project
        run: npm run build
        working-directory: VTI_Glaxy_FE

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GALAXY }}"
          channelId: live
          projectId: galaxy-6ab6e   # đổi thành Project ID của bạn
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
